---
title: "Homework8"
author: "HudsonPlaskoff"
date: "2026-03-22"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(Lock5Data)
```

# BMI Data^[Question 1 complete]

```{r}
Student_Survey_BMI <- StudentSurvey %>%
  mutate(
    BMI = 701*(Weight/Height^2)
  ) %>%
  select(
    Sex,
    Weight,
    Height,
    BMI
  )

knitr::kable(Student_Survey_BMI %>% head(n=6))
```

# Binned BMI Data^[Question 2 complete]

```{r}
Student_Survey_BMI <- Student_Survey_BMI %>%
  mutate(
    BMI_range = case_when(
      BMI < 18.5 ~ "underweight",
      BMI < 25 ~ "healthy weight",
      BMI < 30 ~ "overweight",
      BMI < Inf ~ "obese",
      is.na(BMI) ~ "n/a",
    )
  )

knitr::kable(Student_Survey_BMI %>% head(n=6))
```

# Highest and Lowest BMIs^[Question 3 complete]

```{r}
Student_Survey_BMI_maxmin <- Student_Survey_BMI %>%
  group_by(Sex) %>%
  summarize(
    max=max(BMI, na.rm=TRUE),
    min=min(BMI, na.rm=TRUE)
  )

knitr::kable(Student_Survey_BMI_maxmin %>% head(n=6))
```

# Verbal and Math SAT Scores

```{r}

```

# Z-Score for Total SAT Scores

```{r}

```